from langchain_core.chat_history import BaseChatMessageHistory
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage, SystemMessage
from app.services.db_service import get_chat_history, add_chat_message, clear_chat_history
from typing import List

class SQLiteHistoryAdapter(BaseChatMessageHistory):
    def __init__(self, session_id: str):
        self.session_id = session_id

    @property
    def messages(self) -> List[BaseMessage]:
        """Retrieve messages from DB and convert to LangChain objects."""
        raw_msgs = get_chat_history(self.session_id, limit=50) # Chronological list
        print(f"DEBUG: SQLiteHistoryAdapter loading {len(raw_msgs)} messages for {self.session_id}")
        lc_msgs = []
        for msg in raw_msgs:
            role = msg["role"]
            content = msg["content"]
            if role == "user":
                lc_msgs.append(HumanMessage(content=content))
            elif role == "ai":
                lc_msgs.append(AIMessage(content=content))
            elif role == "tool":
                # Convert 'tool' role to HumanMessage labeled as Observation for ReAct compatibility
                # SystemMessage in the middle of history often breaks Gemini/OpenAI chat models.
                lc_msgs.append(HumanMessage(content=f"Observation: {content}"))
            elif role == "system":
                # Same for random system messages - treat as context/observation
                lc_msgs.append(HumanMessage(content=f"System Notice: {content}"))
        return lc_msgs

    def add_message(self, message: BaseMessage) -> None:
        """Save a LangChain message to DB."""
        print(f"DEBUG: Adapter saving message type: {type(message)} Content: {str(message.content)[:50]}...")
        if isinstance(message, HumanMessage):
             add_chat_message(self.session_id, "user", message.content)
        elif isinstance(message, AIMessage):
             add_chat_message(self.session_id, "ai", message.content)
        elif isinstance(message, SystemMessage):
             # Handle System messages (rarely generated by Agent, but possible)
             add_chat_message(self.session_id, "system", message.content)
        # We don't auto-save ToolMessages here because we handle them manually in langchain_service
        # (Or we could, but StructuredChatAgent usually yields Actions, not ToolMessages directly)

    def clear(self) -> None:
        """Clear session history."""
        clear_chat_history(self.session_id)
